openweathermap:
  api_key:
  cities:
    - name: Sofia
      lat: 42.6977
      lon: 23.3219
    - name: Berlin
      lat: 52.52437
      lon: 13.41053
    - name: Dresden
      lat: 51.0504
      lon: 13.7373

database:
  dbname: ""
  user: ""
  password: ""
  host: ""
  port: 
