openweathermap:
  api_key: ""
  
database:
  dbname: ""
  user: ""
  password: ""
  host: ""
  port: 
  
queries:
  get_city_names: "SELECT city_id, name, latitude, longitude FROM open_weather_app_db.city"
